#!/usr/bin/env bash
# Download the app's three typefaces into apps/web/public/fonts/ and generate the
# @font-face rules that point at them.
#
# WHY SELF-HOST. The design handoff asks for it, and the reasons are concrete:
# a Google Fonts <link> is a request every student's browser makes to a third
# party on every cold load, it is blocked on some campus networks entirely, and
# when it fails the icon font takes the UI with it (Material Symbols renders from
# ligatures — see the note on `.icon` in styles/reep-v2.scss). Self-hosted, the
# fonts are same-origin, cached with the app, and cannot be blocked separately
# from it.
#
# THE ICON FONT IS SUBSET, AND THAT IS NOT AN OPTIMISATION. The full Material
# Symbols Rounded face is 5.2 MB — untenable to ship. Google will subset it to a
# named glyph list, so this requests exactly the glyphs the app uses, read from
# icon-names.txt. Add an icon to a template and you MUST re-run
# collect-icon-names.py and then this script, or that icon renders as nothing.
#
#   python3 tools/fonts/collect-icon-names.py && tools/fonts/fetch-fonts.sh
#
# Re-running is idempotent: files are overwritten, the SCSS is regenerated.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../.." && pwd)"
out_dir="$root/apps/web/public/fonts"
scss="$root/apps/web/src/styles/fonts.scss"

# A modern UA is REQUIRED. Google serves the format it thinks the client can
# read; with curl's default UA it answers with .ttf, which is several times the
# size of the woff2 every browser we support handles.
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"

mkdir -p "$out_dir"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

icons="$(paste -sd, "$here/icon-names.txt")"

# `display=block` for the icon font, not `swap`: swap paints the LIGATURE TEXT
# during the fallback period, which is the exact failure self-hosting is meant to
# remove. block leaves the (clamped, hidden) box empty instead.
declare -A FAMILIES=(
  ["orbitron"]="Orbitron:wght@500;700;900&display=swap"
  ["chakra-petch"]="Chakra+Petch:wght@400;500;600;700&display=swap"
  ["material-symbols-rounded"]="Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,300..600,0..1,-50..200&icon_names=${icons}&display=block"
)

{
  cat <<'HEADER'
/**
 * Self-hosted webfonts — GENERATED by tools/fonts/fetch-fonts.sh. Do not edit.
 *
 * Regenerate with:
 *   python3 tools/fonts/collect-icon-names.py && tools/fonts/fetch-fonts.sh
 *
 * The files live in apps/web/public/fonts/ and are served same-origin from
 * /fonts/, so no third party is contacted to render the UI. Material Symbols is
 * SUBSET to tools/fonts/icon-names.txt — adding an icon to a template without
 * regenerating this file leaves that icon blank.
 */

HEADER
} > "$scss"

for name in "${!FAMILIES[@]}"; do
  echo "→ $name"
  curl -sSf -m 60 -A "$UA" "https://fonts.googleapis.com/css2?family=${FAMILIES[$name]}" -o "$tmp/$name.css"

  i=0
  # Each @font-face block carries its own unicode-range; keeping them separate is
  # what lets a browser skip downloading the latin-ext slice for a latin page.
  python3 - "$tmp/$name.css" "$name" "$out_dir" "$scss" <<'PY'
import pathlib, re, subprocess, sys
css_path, family_slug, out_dir, scss_path = sys.argv[1:5]
css = pathlib.Path(css_path).read_text()
out_dir = pathlib.Path(out_dir)
blocks = re.findall(r"@font-face\s*\{(.*?)\}", css, re.S)
lines = []
for i, block in enumerate(blocks):
    # NOT a `\.woff2$` match. A SUBSET request comes back as
    # https://fonts.gstatic.com/l/font?kit=... with no extension at all, so
    # anchoring on the filename silently skips exactly the font this script
    # exists to fetch. Match any gstatic url and trust the format() hint.
    url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block)
    if not url:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
    style = re.search(r"font-style:\s*([^;]+);", block)
    display = re.search(r"font-display:\s*([^;]+);", block)
    urange = re.search(r"unicode-range:\s*([^;]+);", block)
    # DETERMINISTIC filenames, not an index. index.html preloads two of these
    # by name; numbering them by position means adding a weight renumbers every
    # later file and silently turns those preloads into 404s that fetch a font
    # nobody uses. Name by what the face IS — family, weight, script range — and
    # the name is stable as long as the face is.
    weight_slug = weight.replace(" ", "-")
    if urange and "U+0000-00FF" in urange.group(1):
        range_slug = "latin"
    elif urange:
        range_slug = f"r{i}"
    else:
        range_slug = "all"
    fname = f"{family_slug}-{weight_slug}-{range_slug}.woff2"
    subprocess.run(["curl", "-sSf", "-m", "120", "-o", str(out_dir / fname), url.group(1)], check=True)
    rule = [f"@font-face {{", f"  font-family: '{fam}';"]
    if style:
        rule.append(f"  font-style: {style.group(1).strip()};")
    rule.append(f"  font-weight: {weight};")
    rule.append(f"  font-display: {(display.group(1).strip() if display else 'swap')};")
    rule.append(f"  src: url('/fonts/{fname}') format('woff2');")
    if urange:
        rule.append(f"  unicode-range: {urange.group(1).strip()};")
    rule.append("}")
    lines.append("\n".join(rule))
with open(scss_path, "a") as fh:
    fh.write("\n".join(lines) + "\n\n")
print(f"   {len(lines)} face(s)")
PY
done

echo
echo "Fonts in $out_dir:"
du -ch "$out_dir"/*.woff2 | tail -1
