"""jobs job_applications

Revision ID: 01c7bb72b68d
Revises: efa345768652
Create Date: 2026-08-15 07:45:55.199297
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01c7bb72b68d'
down_revision: Union[str, None] = 'efa345768652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('degree_level', sa.Enum('UG', 'PG', name='degree_level'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('apply_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('posted_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closes_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_cgpa', sa.Float(), nullable=True),
    sa.Column('max_live_backlogs', sa.Integer(), nullable=True),
    sa.Column('import_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ref')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('self_reported', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'job_id', name='uq_job_application')
    )
    op.create_index('ix_jobapp_job', 'job_applications', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobapp_job', table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_table('jobs')
    # ### end Alembic commands ###
