"""attendance_records

Revision ID: 047481d26bbd
Revises: 5b3419986605
Create Date: 2026-08-15 03:22:33.720811
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '047481d26bbd'
down_revision: Union[str, None] = '5b3419986605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_no', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_code', 'session_no', name='uq_attendance')
    )
    op.create_index('ix_attendance_student_date', 'attendance_records', ['student_id', 'session_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_student_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
