"""agent_runs

Revision ID: 094277ababc9
Revises: 2b3f9aa4b8f2
Create Date: 2026-08-15 14:54:56.646035
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision: str = '094277ababc9'
down_revision: Union[str, None] = '2b3f9aa4b8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('STUDENT', 'MENTOR', 'DIRECTOR', 'ADMIN', name='role', create_type=False), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('ANSWERED', 'EXHAUSTED', 'REFUSED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('steps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agentrun_actor_created', 'agent_runs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_agentrun_status', 'agent_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agentrun_status', table_name='agent_runs')
    op.drop_index('ix_agentrun_actor_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
