"""knowledge_base_documents_chunks

Revision ID: 1aa19fa788e9
Revises: d2f7a1c9e4b0
Create Date: 2026-08-15 21:49:23.897685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1aa19fa788e9'
down_revision: Union[str, None] = 'd2f7a1c9e4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='knowledge_status'), server_default='DRAFT', nullable=False),
    sa.Column('audience', sa.String(), server_default='student', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_doc_source_type', 'knowledge_documents', ['source_type'], unique=False)
    op.create_index('ix_knowledge_doc_status_audience', 'knowledge_documents', ['status', 'audience'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('anchor', sa.String(), nullable=True),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunk_document', 'knowledge_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###

    # Postgres full-text GIN index over the chunk text — backs the PRIMARY
    # retrieval path in app/knowledge.py (ts_rank over to_tsvector('english', ...)).
    # Hand-written because Alembic can't autogenerate a functional/expression index.
    op.execute(
        "CREATE INDEX ix_knowledge_chunk_fts "
        "ON knowledge_chunks USING gin (to_tsvector('english', chunk_text))"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunk_fts")
    op.drop_index('ix_knowledge_chunk_document', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_doc_status_audience', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_doc_source_type', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
