"""schedule_items

Revision ID: 1aecd2178ccd
Revises: a80068bf03da
Create Date: 2026-08-15 09:27:51.279485
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1aecd2178ccd'
down_revision: Union[str, None] = 'a80068bf03da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('LAB_SESSION', 'LECTURE', 'CERT_DEADLINE', 'MENTOR_MEETING', name='schedule_type'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_student_starts', 'schedule_items', ['student_id', 'starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_student_starts', table_name='schedule_items')
    op.drop_table('schedule_items')
    # ### end Alembic commands ###
