"""placement_criteria

Revision ID: 2b3f9aa4b8f2
Revises: fea4515cdba5
Create Date: 2026-08-15 14:50:23.277388
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b3f9aa4b8f2'
down_revision: Union[str, None] = 'fea4515cdba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_criteria',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), server_default='Default', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('min_reep_completion_pct', sa.Float(), server_default='80', nullable=False),
    sa.Column('require_core_certs', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('min_attendance_pct', sa.Float(), server_default='85', nullable=False),
    sa.Column('min_cert_completion_pct', sa.Float(), server_default='75', nullable=False),
    sa.Column('min_cgpa', sa.Float(), server_default='6.0', nullable=False),
    sa.Column('max_live_backlogs', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_gap_months', sa.Integer(), server_default='24', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_criteria')
    # ### end Alembic commands ###
