"""mail_logs

Revision ID: 3fd5bf464c0b
Revises: 9ecfa486074d
Create Date: 2026-08-15 15:12:37.636928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fd5bf464c0b'
down_revision: Union[str, None] = '9ecfa486074d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SUPPRESSED', name='mail_status'), server_default='SENT', nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_maillog_kind_sent', 'mail_logs', ['kind', 'sent_at'], unique=False)
    op.create_index('ix_maillog_recipient_sent', 'mail_logs', ['recipient', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_maillog_recipient_sent', table_name='mail_logs')
    op.drop_index('ix_maillog_kind_sent', table_name='mail_logs')
    op.drop_table('mail_logs')
    # ### end Alembic commands ###
