"""swoc_entries

Revision ID: 442f409fe2b2
Revises: 9ac9f4696b0d
Create Date: 2026-08-15 03:33:40.952362
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '442f409fe2b2'
down_revision: Union[str, None] = '9ac9f4696b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swoc_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('PLACEMENT', 'MENTOR', 'PM', name='swoc_source'), nullable=False),
    sa.Column('kind', sa.Enum('STRENGTH', 'WEAKNESS', 'OPPORTUNITY', 'CHALLENGE', name='swoc_kind'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), server_default='3', nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_swoc_student_kind', 'swoc_entries', ['student_id', 'kind'], unique=False)
    op.create_index('ix_swoc_student_source', 'swoc_entries', ['student_id', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_swoc_student_source', table_name='swoc_entries')
    op.drop_index('ix_swoc_student_kind', table_name='swoc_entries')
    op.drop_table('swoc_entries')
    # ### end Alembic commands ###
