"""job_import_runs

Revision ID: 496d83735a1d
Revises: b73e107ffbc2
Create Date: 2026-08-15 15:20:27.488222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '496d83735a1d'
down_revision: Union[str, None] = 'b73e107ffbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_import_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobimport_started', 'job_import_runs', ['started_at'], unique=False)
    op.create_foreign_key('fk_jobs_import_run', 'jobs', 'job_import_runs', ['import_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_import_run', 'jobs', type_='foreignkey')
    op.drop_index('ix_jobimport_started', table_name='job_import_runs')
    op.drop_table('job_import_runs')
    # ### end Alembic commands ###
