"""student_profiles

Revision ID: 4e4ac34a89a7
Revises: f65867efe738
Create Date: 2026-08-15 03:12:56.479753
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4e4ac34a89a7'
down_revision: Union[str, None] = 'f65867efe738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('career_summary', sa.String(), nullable=True),
    sa.Column('placement_eligible', sa.Boolean(), nullable=False),
    sa.Column('interested_in_jobs', sa.Boolean(), nullable=False),
    sa.Column('interested_in_internships', sa.Boolean(), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_upload_id', sa.String(), nullable=True),
    sa.Column('leaderboard_opt_out', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
