"""uploads

Revision ID: 5d48c6c2ffdd
Revises: 094277ababc9
Create Date: 2026-08-15 15:02:36.448917
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d48c6c2ffdd'
down_revision: Union[str, None] = '094277ababc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('CERTIFICATE_PROOF', 'RESUME', 'PROFILE_PHOTO', 'DOCUMENT', name='upload_kind'), nullable=False),
    sa.Column('cert_code', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='upload_status'), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cert_code'], ['certifications.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index('ix_upload_cert', 'uploads', ['cert_code'], unique=False)
    op.create_index('ix_upload_status', 'uploads', ['status'], unique=False)
    op.create_index('ix_upload_student_kind', 'uploads', ['student_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upload_student_kind', table_name='uploads')
    op.drop_index('ix_upload_status', table_name='uploads')
    op.drop_index('ix_upload_cert', table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
