"""skill_claims

Revision ID: 6111de4784aa
Revises: 496d83735a1d
Create Date: 2026-08-15 15:25:55.903222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '6111de4784aa'
down_revision: Union[str, None] = '496d83735a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('claimed_level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_REVIEW', 'VERIFIED', 'REJECTED', name='upload_status', create_type=False), server_default='PENDING_REVIEW', nullable=False),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skillclaim_skill', 'skill_claims', ['skill_id'], unique=False)
    op.create_index('ix_skillclaim_status', 'skill_claims', ['status'], unique=False)
    op.create_index('ix_skillclaim_student_status', 'skill_claims', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skillclaim_student_status', table_name='skill_claims')
    op.drop_index('ix_skillclaim_status', table_name='skill_claims')
    op.drop_index('ix_skillclaim_skill', table_name='skill_claims')
    op.drop_table('skill_claims')
    # ### end Alembic commands ###
