"""mentor_notes

Revision ID: 617fc28a1a31
Revises: bd74d3af53de
Create Date: 2026-08-15 07:14:28.826308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '617fc28a1a31'
down_revision: Union[str, None] = 'bd74d3af53de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mentor_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('linked_action', sa.Enum('NONE', 'FLAGGED', 'NUDGE_SENT', 'ONE_ON_ONE_SCHEDULED', name='mentor_action'), server_default='NONE', nullable=False),
    sa.Column('meeting_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentornote_student_created', 'mentor_notes', ['student_id', 'created_at'], unique=False)
    op.create_index('ix_mentornote_student_meeting', 'mentor_notes', ['student_id', 'meeting_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentornote_student_meeting', table_name='mentor_notes')
    op.drop_index('ix_mentornote_student_created', table_name='mentor_notes')
    op.drop_table('mentor_notes')
    # ### end Alembic commands ###
