"""lab_sessions

Revision ID: 69d81a708980
Revises: 8dc0602056e9
Create Date: 2026-08-15 14:37:53.685934
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69d81a708980'
down_revision: Union[str, None] = '8dc0602056e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('activity', sa.Enum('LECTURE', 'SUPERVISED_LAB', 'ONLINE_COURSE', 'PRACTICE_PROBLEMS', 'GROUP_STUDY', 'ASSIGNMENT', 'PROJECT_WORK', 'READING', 'REVISION', 'MOCK_INTERVIEW', 'PRESENTATION_PREP', 'APTITUDE_PREP', 'INDUSTRY_VISIT', 'MENTOR_MEETING', 'OTHER', name='activity_type'), server_default='ONLINE_COURSE', nullable=False),
    sa.Column('activity_note', sa.String(), nullable=True),
    sa.Column('mode', sa.Enum('INSTRUCTOR_LED', 'SUPERVISED_LAB', 'INDEPENDENT', name='learning_mode'), server_default='SUPERVISED_LAB', nullable=False),
    sa.Column('source', sa.Enum('BADGE', 'LAB_PC', 'MANUAL', 'SELF_REPORTED', name='check_in_source'), server_default='LAB_PC', nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('progress_at_check_in', sa.Float(), nullable=True),
    sa.Column('progress_at_check_out', sa.Float(), nullable=True),
    sa.Column('progress_delta_pct', sa.Float(), nullable=True),
    sa.Column('mentor_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_labsession_course', 'lab_sessions', ['course_code'], unique=False)
    op.create_index('ix_labsession_student_checkin', 'lab_sessions', ['student_id', 'check_in_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labsession_student_checkin', table_name='lab_sessions')
    op.drop_index('ix_labsession_course', table_name='lab_sessions')
    op.drop_table('lab_sessions')
    # ### end Alembic commands ###
