"""one active conversation per owner

Revision ID: 6afb55d18ed8
Revises: d989bec4286d
Create Date: 2026-08-17 00:12:37.011849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6afb55d18ed8'
down_revision: Union[str, None] = 'd989bec4286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_conversation_one_active_per_owner', 'conversations', ['owner_user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_conversation_one_active_per_owner', table_name='conversations', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
