"""skills student_skills

Revision ID: 76bc4771604c
Revises: 7b9f0d2b94c9
Create Date: 2026-08-15 03:54:11.975164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76bc4771604c'
down_revision: Union[str, None] = '7b9f0d2b94c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_skills_category', 'skills', ['category'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('evidence_upload_id', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill')
    )
    op.create_index('ix_student_skills_skill', 'student_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_skills_skill', table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index('ix_skills_category', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
