"""mock_attempts

Revision ID: 7b9f0d2b94c9
Revises: 442f409fe2b2
Create Date: 2026-08-15 03:44:58.432977
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b9f0d2b94c9'
down_revision: Union[str, None] = '442f409fe2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('GD', 'INTERVIEW', 'APTITUDE', name='mock_type'), nullable=False),
    sa.Column('taken_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('evaluator_user_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mock_student_taken', 'mock_attempts', ['student_id', 'taken_on'], unique=False)
    op.create_index('ix_mock_type_taken', 'mock_attempts', ['type', 'taken_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mock_type_taken', table_name='mock_attempts')
    op.drop_index('ix_mock_student_taken', table_name='mock_attempts')
    op.drop_table('mock_attempts')
    # ### end Alembic commands ###
