"""time_sheet_entries

Revision ID: 89c58184d2c4
Revises: 76bc4771604c
Create Date: 2026-08-15 04:40:27.561543
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '89c58184d2c4'
down_revision: Union[str, None] = '76bc4771604c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_sheet_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('activity', sa.Enum('SLEEPING', 'LEISURE', 'LECTURES', 'COURSEWORK', 'SKILLING', name='day_activity'), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'day', 'activity', name='uq_timesheet')
    )
    op.create_index('ix_timesheet_student_day', 'time_sheet_entries', ['student_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timesheet_student_day', table_name='time_sheet_entries')
    op.drop_table('time_sheet_entries')
    # ### end Alembic commands ###
