"""certifications certification_progress

Revision ID: 8dc0602056e9
Revises: fdf358b2dc69
Create Date: 2026-08-15 09:57:11.848558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '8dc0602056e9'
down_revision: Union[str, None] = 'fdf358b2dc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), server_default='Coursera', nullable=False),
    sa.Column('required_hours', sa.Float(), server_default='10', nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('due_week', sa.Integer(), server_default='12', nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_cert_course', 'certifications', ['course_code'], unique=False)
    op.create_table('certification_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('cert_code', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='progress_status', create_type=False), server_default='NOT_STARTED', nullable=False),
    sa.Column('progress_pct', sa.Float(), server_default='0', nullable=False),
    sa.Column('hours_logged', sa.Float(), server_default='0', nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_reported', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['cert_code'], ['certifications.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'cert_code', name='uq_cert_progress')
    )
    op.create_index('ix_certprog_student_status', 'certification_progress', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certprog_student_status', table_name='certification_progress')
    op.drop_table('certification_progress')
    op.drop_index('ix_cert_course', table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
