"""registrations

Revision ID: 9ecfa486074d
Revises: 5d48c6c2ffdd
Create Date: 2026-08-15 15:08:14.047435
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9ecfa486074d'
down_revision: Union[str, None] = '5d48c6c2ffdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_domain', sa.String(), nullable=True),
    sa.Column('usn_pattern', sa.String(), nullable=True),
    sa.Column('degree_level', postgresql.ENUM('UG', 'PG', name='degree_level', create_type=False), nullable=True),
    sa.Column('cohort_id', sa.String(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regrule_enabled_priority', 'registration_rules', ['enabled', 'priority'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('usn', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('degree_level', postgresql.ENUM('UG', 'PG', name='degree_level', create_type=False), server_default='PG', nullable=False),
    sa.Column('cohort_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_VERIFICATION', 'PENDING_REVIEW', 'AUTO_APPROVED', 'APPROVED', 'REJECTED', name='registration_status'), server_default='DRAFT', nullable=False),
    sa.Column('matched_rule_id', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('approved_student_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['registration_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_registration_status_created', 'registrations', ['status', 'created_at'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('registration_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_emailverif_registration', 'email_verifications', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emailverif_registration', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('ix_registration_status_created', table_name='registrations')
    op.drop_table('registrations')
    op.drop_index('ix_regrule_enabled_priority', table_name='registration_rules')
    op.drop_table('registration_rules')
    # ### end Alembic commands ###
