"""leave_requests

Revision ID: a80068bf03da
Revises: d58ecdf6a93c
Create Date: 2026-08-15 09:21:17.074989
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a80068bf03da'
down_revision: Union[str, None] = 'd58ecdf6a93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requester_user_id', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'FIRST_APPROVED', 'APPROVED', 'REJECTED', 'CANCELLED', name='leave_status'), server_default='SUBMITTED', nullable=False),
    sa.Column('first_approver_user_id', sa.String(), nullable=True),
    sa.Column('first_decision', sa.Enum('APPROVED', 'REJECTED', name='leave_decision'), nullable=True),
    sa.Column('first_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_note', sa.String(), nullable=True),
    sa.Column('second_approver_user_id', sa.String(), nullable=True),
    sa.Column('second_decision', sa.Enum('APPROVED', 'REJECTED', name='leave_decision'), nullable=True),
    sa.Column('second_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('second_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_approver_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_requester', 'leave_requests', ['requester_user_id', 'created_at'], unique=False)
    op.create_index('ix_leave_status_created', 'leave_requests', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leave_status_created', table_name='leave_requests')
    op.drop_index('ix_leave_requester', table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
