"""alert_rule_configs

Revision ID: b73e107ffbc2
Revises: 3fd5bf464c0b
Create Date: 2026-08-15 15:16:31.930476
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b73e107ffbc2'
down_revision: Union[str, None] = '3fd5bf464c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rule_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cohort_id', sa.String(), nullable=False),
    sa.Column('rule_key', postgresql.ENUM('NO_CHECKIN_N_DAYS', 'PACE_BELOW_THRESHOLD', 'ATTENDANCE_BELOW_THRESHOLD', 'CERT_OVERDUE', 'LOW_FOCUS_QUALITY', name='alert_rule_key', create_type=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alert_severity', create_type=False), server_default='WARNING', nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'rule_key', name='uq_alertrule_cohort_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_rule_configs')
    # ### end Alembic commands ###
