"""academic_qualifications academic_gaps

Revision ID: bd74d3af53de
Revises: 89c58184d2c4
Create Date: 2026-08-15 04:52:44.930247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd74d3af53de'
down_revision: Union[str, None] = '89c58184d2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_gaps',
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('twelfth_to_grad_mo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('diploma_to_grad_mo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('grad_to_pg_mo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('other_mo', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('academic_qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('TENTH', 'TWELFTH', 'DIPLOMA', 'UNDERGRAD', 'POSTGRAD', name='qualification_level'), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), server_default='100', nullable=False),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_acadqual_student_level', 'academic_qualifications', ['student_id', 'level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acadqual_student_level', table_name='academic_qualifications')
    op.drop_table('academic_qualifications')
    op.drop_table('academic_gaps')
    # ### end Alembic commands ###
