"""conversations messages

Revision ID: c4e4c58eac29
Revises: 3c8af3d95253
Create Date: 2026-08-15 21:31:43.404488
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'c4e4c58eac29'
down_revision: Union[str, None] = '3c8af3d95253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('STUDENT', 'MENTOR', 'DIRECTOR', 'ADMIN', name='role', create_type=False), nullable=False),
    sa.Column('channel', sa.String(), server_default='text', nullable=False),
    sa.Column('consent_state', sa.String(), server_default='none', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_owner_activity', 'conversations', ['owner_user_id', 'last_activity_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), server_default='text', nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_final', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('provider_turn_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'provider_turn_id', name='uq_message_provider_turn')
    )
    op.create_index('ix_message_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_owner_activity', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
