"""placement_offers

Revision ID: d58ecdf6a93c
Revises: 01c7bb72b68d
Create Date: 2026-08-15 09:07:24.147132
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd58ecdf6a93c'
down_revision: Union[str, None] = '01c7bb72b68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('role_type', sa.Enum('FULL_TIME', 'FULL_TIME_PLUS_INTERNSHIP', 'INTERNSHIP', name='offer_role_type'), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('organisation', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('ON_CAMPUS', 'OFF_CAMPUS', 'POOL', 'REFERRAL', name='offer_channel'), server_default='ON_CAMPUS', nullable=False),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('work_mode', sa.Enum('REMOTE', 'ONSITE', 'HYBRID', name='offer_work_mode'), server_default='ONSITE', nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('ctc_inr', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fixed_gross_inr', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bonuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('offer_letter_upload_id', sa.String(), nullable=True),
    sa.Column('loi_upload_id', sa.String(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('bond_details', sa.String(), nullable=True),
    sa.Column('other_benefits', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='offer_status'), server_default='DRAFT', nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offer_student_status', 'placement_offers', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_offer_student_status', table_name='placement_offers')
    op.drop_table('placement_offers')
    # ### end Alembic commands ###
