"""conversation greeted_at

Revision ID: d989bec4286d
Revises: b7e2f4a19c33
Create Date: 2026-08-16 23:19:52.299733
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd989bec4286d'
down_revision: Union[str, None] = 'b7e2f4a19c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('greeted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'greeted_at')
    # ### end Alembic commands ###
