"""v2 UI: time allocation ledger, english baseline, programme milestones

The schema behind the three genuinely-new screens in the v2 student UI:

  time_ledger_days / time_ledger_cells   the Time Allocation Ledger
  english_baselines / …_sections         the English Proficiency Baseline
  student_milestones                     the three landing stage cards
  mentor_notes.title / .location         the Mentor Meeting Log's headings

HAND-WRITTEN, NOT AUTOGENERATED, and the enum handling is why. Autogenerate
emits a bare `sa.Enum(...)` for every enum column it finds, which is correct only
for a type that does not exist yet. `time_ledger_cells.activity` reuses the
EXISTING `day_activity` type created by 89c58184d2c4 (time_sheet_entries), and a
bare sa.Enum there makes the upgrade die on `type "day_activity" already
exists` — AGENTS.md's enum gotcha (b). It is declared with create_type=False
below and is the only enum in this file that is not created here.

The six new types ARE created explicitly, ahead of the tables that use them,
rather than being left to the CREATE TABLE — gotcha (a). Declaring them once at
the top with create_type=False on every column reference is what keeps the
downgrade honest too: each is dropped exactly once at the end.

Revision ID: e4c1b7a9d203
Revises: b41c9e2d7f05
Create Date: 2026-08-25
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e4c1b7a9d203"
down_revision: Union[str, Sequence[str], None] = "b41c9e2d7f05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- enum types -------------------------------------------------------------
#
# Every one of these is referenced with create_type=False at the column, so the
# CREATE happens exactly where `.create(bind)` is called in upgrade().

LEDGER_SLOT = postgresql.ENUM(
    "DAWN", "MORNING", "MIDDAY", "AFTERNOON", "EVENING", "NIGHT",
    name="ledger_slot",
    create_type=False,
)
LEDGER_DAY_STATUS = postgresql.ENUM(
    "DRAFT", "SUBMITTED", name="ledger_day_status", create_type=False
)
ENGLISH_SKILL = postgresql.ENUM(
    "READING", "WRITING", "LISTENING", "SPEAKING", name="english_skill", create_type=False
)
ENGLISH_SECTION_STATUS = postgresql.ENUM(
    "SCORED", "PENDING", name="english_section_status", create_type=False
)
ENGLISH_BASELINE_STATUS = postgresql.ENUM(
    "IN_PROGRESS", "COMPLETE", name="english_baseline_status", create_type=False
)
MILESTONE_STATUS = postgresql.ENUM(
    "NOT_STARTED", "IN_PROGRESS", "COMPLETED", name="milestone_status", create_type=False
)

_NEW_TYPES = (
    LEDGER_SLOT,
    LEDGER_DAY_STATUS,
    ENGLISH_SKILL,
    ENGLISH_SECTION_STATUS,
    ENGLISH_BASELINE_STATUS,
    MILESTONE_STATUS,
)

# EXISTING — created by 89c58184d2c4. Referenced, never created.
DAY_ACTIVITY = postgresql.ENUM(
    "SLEEPING", "LEISURE", "LECTURES", "COURSEWORK", "SKILLING",
    name="day_activity",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in _NEW_TYPES:
        enum_type.create(bind, checkfirst=True)

    # --- Time Allocation Ledger --------------------------------------------
    op.create_table(
        "time_ledger_days",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("status", LEDGER_DAY_STATUS, server_default="DRAFT", nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "day", name="uq_ledger_day"),
    )
    op.create_index("ix_ledger_day_student_day", "time_ledger_days", ["student_id", "day"])

    op.create_table(
        "time_ledger_cells",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ledger_day_id", sa.String(), nullable=False),
        sa.Column("slot", LEDGER_SLOT, nullable=False),
        # The reuse. See the module docstring.
        sa.Column("activity", DAY_ACTIVITY, nullable=False),
        sa.Column("half_hours", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ledger_day_id"], ["time_ledger_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ledger_day_id", "slot", "activity", name="uq_ledger_cell"),
    )
    op.create_index("ix_ledger_cell_day", "time_ledger_cells", ["ledger_day_id"])

    # --- English Proficiency Baseline --------------------------------------
    op.create_table(
        "english_baselines",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("semester", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status", ENGLISH_BASELINE_STATUS, server_default="IN_PROGRESS", nullable=False
        ),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column("band", sa.String(), nullable=True),
        sa.Column("taken_on", sa.Date(), nullable=True),
        sa.Column("strengths", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("focus_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("next_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "report_available", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "semester", name="uq_english_baseline_semester"),
    )
    op.create_index("ix_english_baseline_student", "english_baselines", ["student_id"])

    op.create_table(
        "english_baseline_sections",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("baseline_id", sa.String(), nullable=False),
        sa.Column("skill", ENGLISH_SKILL, nullable=False),
        sa.Column("status", ENGLISH_SECTION_STATUS, server_default="PENDING", nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("band", sa.String(), nullable=True),
        sa.Column("minutes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("subscores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ai_report", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["baseline_id"], ["english_baselines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "skill", name="uq_english_section"),
    )
    op.create_index("ix_english_section_baseline", "english_baseline_sections", ["baseline_id"])

    # --- Programme milestones ----------------------------------------------
    op.create_table(
        "student_milestones",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("student_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("status", MILESTONE_STATUS, server_default="NOT_STARTED", nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["student_id"], ["students.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "key", name="uq_student_milestone"),
    )
    op.create_index("ix_student_milestone_student", "student_milestones", ["student_id"])

    # --- Mentor Meeting Log headings ---------------------------------------
    # Nullable with no backfill: every existing note is a real note that simply
    # never carried a title, and inventing one would put words in a mentor's
    # mouth on a screen the student reads.
    op.add_column("mentor_notes", sa.Column("title", sa.String(), nullable=True))
    op.add_column("mentor_notes", sa.Column("location", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("mentor_notes", "location")
    op.drop_column("mentor_notes", "title")

    op.drop_index("ix_student_milestone_student", table_name="student_milestones")
    op.drop_table("student_milestones")

    op.drop_index("ix_english_section_baseline", table_name="english_baseline_sections")
    op.drop_table("english_baseline_sections")
    op.drop_index("ix_english_baseline_student", table_name="english_baselines")
    op.drop_table("english_baselines")

    op.drop_index("ix_ledger_cell_day", table_name="time_ledger_cells")
    op.drop_table("time_ledger_cells")
    op.drop_index("ix_ledger_day_student_day", table_name="time_ledger_days")
    op.drop_table("time_ledger_days")

    # day_activity is NOT dropped — time_sheet_entries still uses it, and this
    # migration did not create it.
    bind = op.get_bind()
    for enum_type in reversed(_NEW_TYPES):
        enum_type.drop(bind, checkfirst=True)
