"""alerts

Revision ID: efa345768652
Revises: 617fc28a1a31
Create Date: 2026-08-15 07:32:08.324308
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'efa345768652'
down_revision: Union[str, None] = '617fc28a1a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('rule_triggered', sa.Enum('NO_CHECKIN_N_DAYS', 'PACE_BELOW_THRESHOLD', 'ATTENDANCE_BELOW_THRESHOLD', 'CERT_OVERDUE', 'LOW_FOCUS_QUALITY', name='alert_rule_key'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), server_default='WARNING', nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_rule', 'alerts', ['rule_triggered'], unique=False)
    op.create_index('ix_alert_student_resolved', 'alerts', ['student_id', 'resolved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_student_resolved', table_name='alerts')
    op.drop_index('ix_alert_rule', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
