"""courses enrollments

Revision ID: fdf358b2dc69
Revises: cd202d22b107
Create Date: 2026-08-15 09:42:40.888932
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'fdf358b2dc69'
down_revision: Union[str, None] = 'cd202d22b107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', postgresql.ENUM('REBOOT', 'EXCEL', 'EXCEL_ADVANCED', 'ELEVATE', name='stage', create_type=False), nullable=False),
    sa.Column('dimension', sa.Enum('PROFESSIONAL', 'THINKING', 'TECHNICAL', 'METAPHYSICAL', name='dimension'), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('teaching_hours', sa.Float(), server_default='0', nullable=False),
    sa.Column('self_learning_hours_required', sa.Float(), server_default='0', nullable=False),
    sa.Column('model_type', sa.Enum('TEACHING_PLUS_SELF_LEARN', 'SUPERVISED_SELF_LEARN', 'INSTRUCTOR_LED', name='course_model'), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), server_default='16', nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_courses_stage', 'courses', ['stage'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='progress_status'), server_default='IN_PROGRESS', nullable=False),
    sa.Column('teaching_hours_attended', sa.Float(), server_default='0', nullable=False),
    sa.Column('self_learning_hours_logged', sa.Float(), server_default='0', nullable=False),
    sa.Column('lectures_attended', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lectures_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_code', name='uq_enrollment')
    )
    op.create_index('ix_enrollment_course', 'enrollments', ['course_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_course', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_courses_stage', table_name='courses')
    op.drop_table('courses')
    postgresql.ENUM(name='progress_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='course_model').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='dimension').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
