-- CreateEnum
CREATE TYPE "ActivityType" AS ENUM ('LECTURE', 'SUPERVISED_LAB', 'ONLINE_COURSE', 'PRACTICE_PROBLEMS', 'GROUP_STUDY', 'ASSIGNMENT', 'PROJECT_WORK', 'READING', 'REVISION', 'MOCK_INTERVIEW', 'PRESENTATION_PREP', 'APTITUDE_PREP', 'INDUSTRY_VISIT', 'MENTOR_MEETING', 'OTHER');

-- AlterTable
ALTER TABLE "lab_sessions" ADD COLUMN     "activity" "ActivityType" NOT NULL DEFAULT 'ONLINE_COURSE',
ADD COLUMN     "activityNote" TEXT;
