# Importing the model modules registers them on Base.metadata (for create_all
# and Alembic autogenerate). Add new model modules here as the schema grows.
from . import academic_history  # noqa: F401
from . import academics  # noqa: F401
from . import agent_run  # noqa: F401
from . import alert  # noqa: F401
from . import alumni  # noqa: F401
from . import attendance  # noqa: F401
from . import badge  # noqa: F401
from . import certification  # noqa: F401
from . import companion  # noqa: F401
from . import cohort  # noqa: F401
from . import conversation  # noqa: F401
from . import course  # noqa: F401
from . import english_baseline  # noqa: F401
from . import feedback  # noqa: F401
from . import interview  # noqa: F401
from . import job  # noqa: F401
from . import job_import_run  # noqa: F401
from . import knowledge  # noqa: F401
from . import lab  # noqa: F401
from . import leave  # noqa: F401
from . import mail  # noqa: F401
from . import mentor_note  # noqa: F401
from . import milestone  # noqa: F401
from . import mock_test  # noqa: F401
from . import offer  # noqa: F401
from . import placement_criteria  # noqa: F401
from . import student_profile  # noqa: F401
from . import registration  # noqa: F401
from . import redesign  # noqa: F401
from . import resume  # noqa: F401
from . import resume_profile  # noqa: F401
from . import schedule  # noqa: F401
from . import skill  # noqa: F401
from . import staff_upskilling  # noqa: F401
from . import swoc  # noqa: F401
from . import time_ledger  # noqa: F401
from . import timesheet  # noqa: F401
from . import upload  # noqa: F401
from . import user  # noqa: F401
from . import voice_worker  # noqa: F401
